version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - ${PORT}:3000
    depends_on:
      - mongo
      - postgres
    volumes:
      - ./:/madmax/usr/app
      - /madmax/usr/app/.pnpm-store/
      - /madmax/usr/app/node_modules/
