export enum Skill {
  JAVA = 'java',
  JAVASCRIPT = 'javascript',
  REACT = 'react',
  TYPESCRIPT = 'typescript',
  POSTGRESQL = 'postgresql',
  MATERIAL_UI = 'mui',
  TAILWIND_CSS = 'tailwindcss',
  GIT = 'git',
  GIT_HUB = 'github',
  GIT_LAB = 'gitlab',
  ARDUINO = 'arduino',
  C_CPP = 'c-cpp',
  RUBY_ON_RAILS = 'ruby-on-rails',
  VUE_JS = 'vuejs',
  DOCKER = 'docker',
  PYTHON = 'python',
  KOTLIN = 'kotlin',
  NEST_JS = 'nestjs',
  NODE_JS = 'nodejs',
  SPRING_BOOT = 'spring',
  MONGO_DB = 'mongodb',
  PRISMA = 'prisma',
  PLAYWRIGHT = 'playwright',
}
