export enum Skill {
  JAVA = 'java',
  JAVASCRIPT = 'javascript',
  REACT = 'react',
  TYPESCRIPT = 'typescript',
  POSTGRESQL = 'postgresql',
  MARIA_DB = 'mariadb',
  MATERIAL_UI = 'mui',
  GIT = 'git',
  ARDUINO = 'arduino',
  C_CPP = 'c-cpp',
  RUBY_ON_RAILS = 'ruby-on-rails',
  VUE_JS = 'vuejs',
  DOCKER = 'docker',
  PYTHON = 'python',
  KOTLIN = 'kotlin',
  NEST_JS = 'nestjs',
  SPRING_BOOT = 'spring',
  MONGO_DB = 'mongodb',
  SQLITE = 'sqlite',
}
