/**
 * @see getSkillDetails()
 */
export enum Skill {
  ARDUINO = 'arduino',
  AWS = 'aws',
  C_CPP = 'c-cpp',
  DOCKER = 'docker',
  GIT = 'git',
  GIT_HUB = 'github',
  GIT_LAB = 'gitlab',
  JAVA = 'java',
  JAVASCRIPT = 'javascript',
  JENKINS = 'jenkins',
  MATERIAL_UI = 'mui',
  MONGO_DB = 'mongodb',
  NEST_JS = 'nestjs',
  NEXT_JS = 'nextjs',
  NODE_JS = 'nodejs',
  PLAYWRIGHT = 'playwright',
  POSTGRESQL = 'postgresql',
  PRISMA = 'prisma',
  PYTHON = 'python',
  REACT = 'react',
  RUBY_ON_RAILS = 'ruby-on-rails',
  REDIS = 'redis',
  SPRING_BOOT = 'spring',
  TAILWIND_CSS = 'tailwindcss',
  TYPESCRIPT = 'typescript',
  VUE_JS = 'vuejs',
}
