#!/bin/bash
#
# Copyright (c) 2022 VEDA GmbH. All rights reserved.
# Use is subject to license terms.
#
. "$(dirname "$0")/_/husky.sh"

# read commit message
message=$(cat "$1")
# split commit message on new line
readarray -t commitMessageLines <<<"$message"
commitMessageHeader=${commitMessageLines[0]}

commitMessagePattern="^(WIP )?.+ #[0-9]+$"
branchPattern="([0-9]+[\w\d-].+|main|dependabot.+)"
mergePattern="^Merge( remote-tracking)? branch '(origin/)?${branchPattern}'( into ${branchPattern})?$"

if ! [[ ${commitMessageHeader} =~ $commitMessagePattern ]]; then
  if ! [[ ${commitMessageHeader} =~ $mergePattern ]]; then
    echo "🚨 Wrong commit message! The commit message must have this format:"
    echo "[ID main task] [Task Summary]"
    echo ""
    echo "[Description]"
    echo "-"
    echo "Example:"
    echo "#1 Husky konfigurieren"
    echo ""
    echo "Did fancy stuff"
    echo "-"
    echo "Your commit message:"
    echo "${message}"
    exit 1
  fi
fi
