name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  release:
    needs: ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: package.json version
        uses: technote-space/package-version-check-action@v1
      - name: Changelog
        id: changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

  deploy:
    needs: release
    uses: ./.github/workflows/Deploy.yml
    with:
      tag: ${{ github.event.inputs.tag }}
