name: Release

on:
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  release:
    needs: ci
    runs-on: ubuntu-latest

    outputs:
      new-version: ${{ steps.bump-semver.outputs.new_version }}

    steps:
      ## Setup
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      ## Change package.json version
      - name: package.json version
        uses: technote-space/package-version-check-action@v1
      
      ## Get release informations
      - name: Generate release label
        id: release-label
        uses: actions-ecosystem/action-release-label@v1
      
      - name: Get last version
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        if: ${{ steps.release-label.outputs.level != null }}
      
      - name: Update version
        id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}
      
      - name: Changelog
        id: changelog
        uses: scottbrenner/generate-changelog-action@master
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          from-tag: ${{ steps.get-latest-tag.outputs.tag }}
          to-tag: HEAD
        env:
          REPO: ${{ github.repository }}
      
      ## Create release
      - name: Create Release
        id: create_release
        if: ${{ steps.release-label.outputs.level != null }}
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
          release_name: Release ${{ steps.bump-semver.outputs.new_version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

  deploy:
    needs: release
    uses: ./.github/workflows/Deploy.yml
    with:
      tag: ${{ needs.release.outputs.new-version }}
