name: Release

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.TOKEN }}
      - name: Create release ${{ steps.changelog.outputs.tag }}
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
